adding gssapi_krb5 support (Michael)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CPP EGREP LIBOBJS PREFER_SO_TRUE PREFER_SO_FALSE OPENSSL_INCLUDES OPENSSL_LDFLAGS OPENSSL_LIBS HAVE_OPENSSL_TRUE HAVE_OPENSSL_FALSE KRB5_CONFIG KRB5_CFLAGS KRB5_LDFLAGS HAVE_KRB5_TRUE HAVE_KRB5_FALSE PAM_INCLUDES PAM_LDFLAGS HAVE_PAM_TRUE HAVE_PAM_FALSE CCLIENT_INCLUDES CCLIENT_LIBS HAVE_CCLIENT_TRUE HAVE_CCLIENT_FALSE LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CPP EGREP LIBOBJS PREFER_SO_TRUE PREFER_SO_FALSE OPENSSL_INCLUDES OPENSSL_LDFLAGS OPENSSL_LIBS HAVE_OPENSSL_TRUE HAVE_OPENSSL_FALSE KRB5_CONFIG KRB5_CFLAGS KRB5_LDFLAGS HAVE_KRB5_TRUE HAVE_KRB5_FALSE KRB5_GSSAPI_CFLAGS KRB5_GSSAPI_LIBS HAVE_KRB5_GSSAPI_TRUE HAVE_KRB5_GSSAPI_FALSE PAM_INCLUDES PAM_LDFLAGS HAVE_PAM_TRUE HAVE_PAM_FALSE CCLIENT_INCLUDES CCLIENT_LIBS HAVE_CCLIENT_TRUE HAVE_CCLIENT_FALSE LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -4185,8 +4185,10 @@ if test "${with_so_preference+set}" = set; then
 fi;
  if test "${PREFER_SO}" = "shared" -o "${PREFER_SO}" = "so" -o "${PREFER_SO}" = "yes" ; then
   PREFER_SO="yes"
+  :
  else
   PREFER_SO="no"
+  :
  fi
 
 
@@ -4436,6 +4438,7 @@ echo "${ECHO_T}found ${KRB5_CONFIG}" >&6
 
 
 
+   :
   fi
  fi
 
@@ -4448,6 +4451,29 @@ else
   HAVE_KRB5_FALSE=
 fi
 
+
+
+
+ HAVE_KRB5_GSSAPI="no"
+ if test "${HAVE_KRB5}" = "yes" -a "${KRB5_CONFIG}" != "" ; then
+  HAVE_KRB5_GSSAPI="yes"
+  KRB5_GSSAPI_CFLAGS="`${KRB5_CONFIG} --cflags gssapi`"
+  KRB5_GSSAPI_LIBS="`${KRB5_CONFIG} --libs gssapi`"
+
+
+  :
+ else
+  :
+ fi
+
+
+if test "${HAVE_KRB5_GSSAPI}" = "yes" ; then
+  HAVE_KRB5_GSSAPI_TRUE=
+  HAVE_KRB5_GSSAPI_FALSE='#'
+else
+  HAVE_KRB5_GSSAPI_TRUE='#'
+  HAVE_KRB5_GSSAPI_FALSE=
+fi
 
 
 
@@ -4610,9 +4636,9 @@ echo "$as_me: error: a working c-client installation is required for building ma
 
  else
 
-        for p in `eval "echo {${CCLIENTLOCATIONS}}{,/c-client,/lib/c-client,/include/c-client,/include}"` ; do
-   echo "$as_me:$LINENO: checking for c-client.h in $p" >&5
+         echo "$as_me:$LINENO: checking for c-client.h in $p" >&5
 echo $ECHO_N "checking for c-client.h in $p... $ECHO_C" >&6
+  for p in `eval "echo {${CCLIENTLOCATIONS}}{,/c-client,/lib/c-client,/include/c-client,/include}"` ; do
    if test -r "${p}/c-client.h" -a -r "${p}/linkage.h" -a -r "${p}/linkage.c" ; then
     CCLIENT_INCLUDES="-I${p}"
     CCLIENT_LINKAGE_H="${p}/linkage.h"
@@ -4654,8 +4680,8 @@ echo "$as_me: error: a working c-client installation is required for building ma
 
    else
 
-                echo "$as_me:$LINENO: checking whether c-client built with kerberos support" >&5
-echo $ECHO_N "checking whether c-client built with kerberos support... $ECHO_C" >&6
+                echo "$as_me:$LINENO: checking whether c-client built with kerberos gssapi support" >&5
+echo $ECHO_N "checking whether c-client built with kerberos gssapi support... $ECHO_C" >&6
     cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
@@ -4683,7 +4709,7 @@ echo "${ECHO_T}no" >&6
 fi
 rm -f conftest*
 
-    if test "${need_krb}" = "yes" -a "${HAVE_KRB5}" != "yes" ; then
+    if test "${need_krb}" = "yes" -a "${HAVE_KRB5_GSSAPI}" != "yes" ; then
 
  { { echo "$as_me:$LINENO: error: a working c-client installation is required for building mailsync" >&5
 echo "$as_me: error: a working c-client installation is required for building mailsync" >&2;}
@@ -4691,7 +4717,7 @@ echo "$as_me: error: a working c-client installation is required for building ma
 
     else
      if test "${need_krb}" = "yes" ; then
-      CCLIENT_LIBS="${CCLIENT_LIBS} ${KRB5_LDFLAGS}"
+      CCLIENT_LIBS="${CCLIENT_LIBS} ${KRB5_GSSAPI_LIBS}"
      fi
 
                     echo "$as_me:$LINENO: checking whether c-client requires ssl linkage" >&5
@@ -5045,6 +5071,13 @@ if test -z "${HAVE_KRB5_TRUE}" && test -z "${HAVE_KRB5_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_KRB5\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"HAVE_KRB5\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_KRB5_GSSAPI_TRUE}" && test -z "${HAVE_KRB5_GSSAPI_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_KRB5_GSSAPI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_KRB5_GSSAPI\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -5649,6 +5682,10 @@ s,@KRB5_CFLAGS@,$KRB5_CFLAGS,;t t
 s,@KRB5_LDFLAGS@,$KRB5_LDFLAGS,;t t
 s,@HAVE_KRB5_TRUE@,$HAVE_KRB5_TRUE,;t t
 s,@HAVE_KRB5_FALSE@,$HAVE_KRB5_FALSE,;t t
+s,@KRB5_GSSAPI_CFLAGS@,$KRB5_GSSAPI_CFLAGS,;t t
+s,@KRB5_GSSAPI_LIBS@,$KRB5_GSSAPI_LIBS,;t t
+s,@HAVE_KRB5_GSSAPI_TRUE@,$HAVE_KRB5_GSSAPI_TRUE,;t t
+s,@HAVE_KRB5_GSSAPI_FALSE@,$HAVE_KRB5_GSSAPI_FALSE,;t t
 s,@PAM_INCLUDES@,$PAM_INCLUDES,;t t
 s,@PAM_LDFLAGS@,$PAM_LDFLAGS,;t t
 s,@HAVE_PAM_TRUE@,$HAVE_PAM_TRUE,;t t
